routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\BannerController;
use App\Http\Controllers\DoctorController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\AppointmentController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontController::class, 'welcomePage'])->name('welcome');
Route::get('/doctor', [FrontController::class, 'doctors'])->name('doctors');
Route::post('/search', [FrontController::class, 'search'])->name('search');
// Route::get('/category', [FrontController::class, 'category'])->name('category');

Route::get('admin/home', [HomeController::class, 'adminHome'])->name('admin.home')->middleware('is_admin');

Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('banners', BannerController::class);
Route::resource('doctors', DoctorController::class);
Route::resource('categories', CategoryController::class);
Route::get('appointment/create/{id}', [AppointmentController::class, 'create'])->name('appointment.create')->middleware('auth');
Route::post('appointment/create', [AppointmentController::class, 'store'])->name('appointment.store')->middleware('auth');
Route::get('appointment/index', [AppointmentController::class, 'index'])->name('appointment.index')->middleware('is_admin');

app/Models/Doctor.php
<?php

namespace App\Models;

use App\Http\Controllers\DoctorController;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Doctor extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'specialist',
        'chamber',
        'cost',
        'cat_id',
    ];

    public function categories() {

        return $this->belongsTo(Category::class, 'cat_id');
    }
}

app/Http/Controllers/DoctorController.php
<?php

namespace App\Http\Controllers;

use App\Models\Doctor;
use App\Http\Requests\DoctorRequest;
use App\Models\Category;

class DoctorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['doctors'] = Doctor::with('categories')->get();
        // dd($data);

        return view('admin.doctor.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['categories'] = Category::pluck('name', 'id');

        return view('admin.doctor.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  App\Http\Requests\DoctorRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(DoctorRequest $request)
    {
        // dd($request->all());
        $doctor = Doctor::create([
            'cat_id' => $request->get('cat_id'),
            'name' => $request->get('name'),
            'specialist' => $request->get('specialist'),
            'chamber' => $request->get('chamber'),
            'cost' => $request->get('cost'),
        ]);
        //  dd($doctor);
        if(empty($doctor)) {
            return redirect()->back()->withInput()->with('ERROR', __('Failed to created'));
        }
        return redirect()->route('doctors.index')->with('SUCCESS', __('Doctor has been created successfully'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Doctor  $doctor
     * @return \Illuminate\Http\Response
     */
    public function show(Doctor $doctor)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Doctor  $doctor
     * @return \Illuminate\Http\Response
     */
    public function edit(Doctor $doctor)
    {
        $data['categories'] = Category::all();
        $data['doctor'] = $doctor;

        return view('admin.doctor.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Doctor  $doctor
     * @return \Illuminate\Http\Response
     */
    public function update(DoctorRequest $request, Doctor $doctor)
    {
        if($doctor->update([
            'cat_id' => $request->get('cat_id'),
            'name' => $request->get('name'),
            'specialist' => $request->get('specialist'),
            'chamber' => $request->get('chamber'),
            'cost' => $request->get('cost'),
        ])) {
            return redirect()->route('doctors.index')->with('SUCCESS', __('Doctor has been updated successfully'));
        }
        return redirect()->back()->withInput()->with('ERROR', __('Failed to updated'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Doctor  $doctor
     * @return \Illuminate\Http\Response
     */
    public function destroy(Doctor $doctor)
    {
        // dd($doctor);
        if($doctor->delete()) {
            return redirect()->route('doctors.index')->with("SUCCESS", __("Doctor has been deleted successfully"));
        }
        return redirect()->back()->withInput()->with("ERROR", __("Failed to deleted"));
    }
}

resources/views/admin/doctor/_form.blade.php
<div class="form-group row">
    <label class="col-form-label col-md-2">Name</label>
    <div class="col-md-10">
        <input class="form-control" type="text" name="name" id="name" value="{{ old('name', isset($doctor) ? $doctor->name : '') }}">
        <p class="text-red-600">{{ $errors->first('name') }}</p>
    </div>
    <label class="col-form-label col-md-2">Category</label>
    <div class="col-md-10">
        <select class="form-control" name="cat_id" id="cat_id">
            <option value="">Select Category</option>
            @foreach ($categories as $key => $value)
                <option value="{{ $key }}">{{ $value }}</option>
            @endforeach
        </select>
        <p class="text-red-600">{{ $errors->first('cat_id') }}</p>
    </div>
    <label class="col-form-label col-md-2">Specialist</label>
    <div class="col-md-10">
        <input class="form-control" type="text" name="specialist" id="specialist" value="{{ old('specialist', isset($doctor) ? $doctor->specialist : '') }}">
        <p class="text-red-600">{{ $errors->first('specialist') }}</p>
    </div>
    <label class="col-form-label col-md-2">Chamber</label>
    <div class="col-md-10">
        <input class="form-control" type="text" name="chamber" id="chamber" value="{{ old('chamber', isset($doctor) ? $doctor->chamber : '') }}">
        <p class="text-red-600">{{ $errors->first('chamber') }}</p>
    </div>
    <label class="col-form-label col-md-2">Cost</label>
    <div class="col-md-10">
        <input class="form-control" type="number" name="cost" id="cost" min="0" value="{{ old('cost', isset($doctor) ? $doctor->cost : '') }}">
        <p class="text-red-600">{{ $errors->first('cost') }}</p>
    </div>
    <button class="btn btn-primary" type="submit">{{ $buttonText }}</button>
</div>

resources/views/admin/doctor/create.blade.php
@extends('layouts.admin')
@section('page_title', 'Add New Doctor')
@section('container')

<!-- Page Header -->
<div class="page-header">
    <div class="row">
        <div class="col">
            <h3 class="page-title">Add New Doctor</h3>
        </div>
    </div>
</div>
<!-- /Page Header -->

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Form</h4>
            </div>
            <div class="card-body">
                <form action="{{ route('doctors.store') }}" method="post">
                    @csrf
                    @include('admin.doctor._form', ['buttonText' => __('Create')])
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/doctor/edit.blade.php
@extends('layouts.admin')
@section('page_title', 'Edit Doctor')
@section('container')

<!-- Page Header -->
<div class="page-header">
    <div class="row">
        <div class="col">
            <h3 class="page-title">Edit Doctor</h3>
        </div>
    </div>
</div>
<!-- /Page Header -->

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Form</h4>
            </div>
            <div class="card-body">
                <form action="{{ route('doctors.update', $doctor->id) }}" method="post">
                    @csrf
                    @method('PUT')
                    @include('admin.doctor._form', ['buttonText' => __('Edit')])
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/doctor/index.blade.php
@extends('layouts.admin')
@section('page_title', 'Doctors')
@section('container')

<!-- Page Header -->
<div class="page-header">
    <div class="row">
        <div class="col">
            <button class="btn btn-primary">
                <a href="{{ route('doctors.create') }}">
                    <h3 class="page-title">Add New Doctor</h3>
                </a>
            </button>
        </div>
    </div>
</div>
<!-- /Page Header -->

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Doctor</h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table mb-0">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Category</th>
                                <th>Specialist</th>
                                <th>Chamber</th>
                                <th>Visit</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($doctors as $doctor)
                                <tr>
                                    <td>{{ $doctor->id }}</td>
                                    <td>{{ $doctor->name }}</td>
                                    <td>{{ $doctor->categories->name }}</td>
                                    <td>{{ $doctor->specialist }}</td>
                                    <td>{{ $doctor->chamber }}</td>
                                    <td>{{ $doctor->cost }}</td>
                                    <td>
                                        <a href="{{ route('doctors.edit', $doctor->id) }}">
                                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                        </a>
                                        | <a class="delete-row" href="{{ route('doctors.destroy', $doctor->id) }}">
                                            <i class="fa fa-trash-o" style="color:red" aria-hidden="true"></i>
                                            </a>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="5" align="center">No doctor found</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection