routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\BannerController;
use App\Http\Controllers\DoctorController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\AppointmentController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontController::class, 'welcomePage'])->name('welcome');
Route::get('/doctor', [FrontController::class, 'doctors'])->name('doctors');
Route::post('/search', [FrontController::class, 'search'])->name('search');
// Route::get('/category', [FrontController::class, 'category'])->name('category');

Route::get('admin/home', [HomeController::class, 'adminHome'])->name('admin.home')->middleware('is_admin');

Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('banners', BannerController::class);
Route::resource('doctors', DoctorController::class);
Route::resource('categories', CategoryController::class);
Route::get('appointment/create/{id}', [AppointmentController::class, 'create'])->name('appointment.create')->middleware('auth');
Route::post('appointment/create', [AppointmentController::class, 'store'])->name('appointment.store')->middleware('auth');
Route::get('appointment/index', [AppointmentController::class, 'index'])->name('appointment.index')->middleware('is_admin');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'image',
    ];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Http\Requests\CategoryRequest;
use Illuminate\Support\Facades\Storage;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['categories'] = Category::all();

        return view('admin.category.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  App\Http\Requests\CategoryRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        $path = $request->file('image')->store('images/category');
        if(!$path) {
            return redirect()->back()->withInput()->with("ERROR", __("Failed to upload image"));
        }

        $category = Category::create([
            'image' => $path,
            'name' => $request->get('name'),
        ]);
        if(empty($category)) {
            return redirect()->back()->withInput();
        }
        return redirect()->route('categories.index')->with("SUCCESS", __("Category has been created successfully"));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $data['categories'] = $category;

        return view('admin.category.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, Category $category)
    {
        if($request->hasFile('image')) {
            if($category->image) {
                Storage::delete($category->image);
            }
            $path = $request->file('image')->store('images/category');
        }
        if($category->update([
            $category->name = $request->get('name'),
            $category->image = $path
        ])) {
            return redirect()->route('categories.index')->with('SUCCESS', __('Category has been updated successfully'));
        }
        return redirect()->back()->withInput()->with('ERROR', __('Failed to updated'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        Storage::delete($category->image);
        if($category->delete()) {
            return redirect()->back()->with('SUCCESS', __('Category has been deleted'));
        }
        return redirect()->back()->with('ERROR', __('Failed to delete Category'));
    }
}

resources/views/admin/category/_form.blade.php
<div class="form-group row">
    <label class="col-form-label col-md-2">File Input</label>
    <div class="col-md-10">
        <input class="form-control" type="file" name="image" id="image">
        <p class="text-red-600">{{ $errors->first('image') }}</p>
    </div>
    <label class="col-form-label col-md-2">Name</label>
    <div class="col-md-10">
        <input class="form-control" type="text" name="name" id="name" value="{{ old('name', isset($categories) ? $categories->name: '') }}">
        <p class="text-red-600">{{ $errors->first('name') }}</p>
    </div>
    <button class="btn btn-primary" type="submit">{{ $buttonText }}</button>
</div>

resources/views/admin/category/create.blade.php
@extends('layouts.admin')
@section('page_title', 'Add Category')
@section('container')

<!-- Page Header -->
<div class="page-header">
    <div class="row">
        <div class="col">
            <h3 class="page-title">Add Category</h3>
        </div>
    </div>
</div>
<!-- /Page Header -->

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Form</h4>
            </div>
            <div class="card-body">
                <form action="{{ route('categories.store') }}" method="post" enctype="multipart/form-data">
                    @csrf
                    @include('admin.category._form', ['buttonText' => __('Create')])
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/category/edit.blade.php
@extends('layouts.admin')
@section('page_title', 'Edit Category')
@section('container')

<!-- Page Header -->
<div class="page-header">
    <div class="row">
        <div class="col">
            <h3 class="page-title">Edit Category</h3>
        </div>
    </div>
</div>
<!-- /Page Header -->

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Form</h4>
            </div>
            <div class="card-body">
                <form action="{{ route('categories.update', $categories->id) }}" method="post" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    @include('admin.category._form', ['buttonText' => __('Edit')])
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/category/index.blade.php
@extends('layouts.admin')
@section('page_title', 'Categories')
@section('container')

<!-- Page Header -->
<div class="page-header">
    <div class="row">
        <div class="col">
            <button class="btn btn-primary">
                <a href="{{ route('categories.create') }}">
                    <h3 class="page-title">Add Category</h3>
                </a>
            </button>
        </div>
    </div>
</div>
<!-- /Page Header -->

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Categories</h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table mb-0">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Image</th>
                                <th>Name</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($categories as $category)
                                <tr>
                                    <td>{{ $category->id }}</td>
                                    <td>
                                        <img src="{{ asset($category->image) }}" alt="image" width="100" height="100">
                                    </td>
                                    <td>{{ $category->name }}</td>
                                    <td>
                                        <a href="{{ route('categories.edit', $category->id) }}">
                                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                             | <a class="delete-row" data-confirm="Are you sure to delete this?" href="{{ route('categories.destroy', $category->id) }}">
                                                 <i class="fa fa-trash-o" style="color:red" aria-hidden="true"></i>
                                             </a>
                                        </a>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="3" align="center">No categories found</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection