routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\BannerController;
use App\Http\Controllers\DoctorController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\AppointmentController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontController::class, 'welcomePage'])->name('welcome');
Route::get('/doctor', [FrontController::class, 'doctors'])->name('doctors');
Route::post('/search', [FrontController::class, 'search'])->name('search');
// Route::get('/category', [FrontController::class, 'category'])->name('category');

Route::get('admin/home', [HomeController::class, 'adminHome'])->name('admin.home')->middleware('is_admin');

Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('banners', BannerController::class);
Route::resource('doctors', DoctorController::class);
Route::resource('categories', CategoryController::class);
Route::get('appointment/create/{id}', [AppointmentController::class, 'create'])->name('appointment.create')->middleware('auth');
Route::post('appointment/create', [AppointmentController::class, 'store'])->name('appointment.store')->middleware('auth');
Route::get('appointment/index', [AppointmentController::class, 'index'])->name('appointment.index')->middleware('is_admin');

app/Models/Banner.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Banner extends Model
{
    use HasFactory;

    protected $fillable = [
        'banner',
    ];
}

app/Http/Controllers/BannerController.php
<?php

namespace App\Http\Controllers;

use App\Models\Banner;
use App\Http\Requests\BannerRequest;
use Illuminate\Support\Facades\Storage;

class BannerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['banners'] = Banner::all();

        return view('admin.banner.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.banner.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  App\Http\Requests\BannerRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BannerRequest $request)
    {
        // dd($request->all());

        $path = $request->file('banner')->store('images/banner');
        if(!$path) {
            return redirect()->back()->with("ERROR", __("Failed to upload image"));
        }

        $banner = Banner::create([
            'banner' => $path,
        ]);
        if(empty($banner)) {
            return redirect()->back();
        }
        return redirect()->route('banners.index')->with("SUCCESS", __("Banner has been created successfully"));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Banner  $banner
     * @return \Illuminate\Http\Response
     */
    public function show(Banner $banner)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Banner  $banner
     * @return \Illuminate\Http\Response
     */
    public function edit(Banner $banner)
    {
        $data['banner'] = $banner;

        return view('admin.banner.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  App\Http\Requests\BannerRequest  $request
     * @param  \App\Models\Banner  $banner
     * @return \Illuminate\Http\Response
     */
    public function update(BannerRequest $request, Banner $banner)
    {
        // dd($request->file());
        if($request->hasFile('banner')) {
            if($banner->banner) {
                storage::delete($banner->banner);
            }
            $path = $request->file('banner')->store('images/banner');

        }
        if($banner->update([
            'banner' => $path,
        ])) {
            return redirect()->route('banners.index')->with('SUCCESS', __('Banner has been updated successfully'));
        }
        return redirect()->back()->with("ERROR", __('Failed to updated'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Banner  $banner
     * @return \Illuminate\Http\Response
     */
    public function destroy(Banner $banner)
    {
        //  dd($banner);
        // if($banner->banner) {
        //     storage::delete($banner->banner);
        //     return redirect()->route('banners.index')->with('SUCCESS', __('Banner has been deleted successfully'));
        // }
        // return redirect()->back()->with('ERROR', __('Failed to delete'));

        storage::delete($banner->banner);
        if($banner->delete()) {
            return redirect()->back()->with('SUCCESS', __('Banner has been deleted successfully'));
        }
        return redirect()->back()->with('ERROR', __('Failed to delete'));
    }
}

resources/views/admin/banner/_form.blade.php
<div class="form-group row">
    <label class="col-form-label col-md-2">File Input</label>
    <div class="col-md-10">
        <input class="form-control" type="file" name="banner" id="banner">
        <p class="text-red-600">{{ $errors->first('banner') }}</p>
    </div>
    <button class="px-4 py-2 bg-green-600" type="submit">{{ $buttonText }}</button>
</div>

resources/views/admin/banner/create.blade.php
@extends('layouts.admin')
@section('page_title', 'Add Banner')
@section('container')

<!-- Page Header -->
<div class="page-header">
    <div class="row">
        <div class="col">
            <h3 class="page-title">Add Banner</h3>
        </div>
    </div>
</div>
<!-- /Page Header -->

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Form</h4>
            </div>
            <div class="card-body">
                <form action="{{ route('banners.store') }}" method="post" enctype="multipart/form-data">
                    @csrf
                    @include('admin.banner._form', ['buttonText' => __('Create')])
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/banner/edit.blade.php
@extends('layouts.admin')
@section('page_title', 'Edit Banner')
@section('container')

<!-- Page Header -->
<div class="page-header">
    <div class="row">
        <div class="col">
            <h3 class="page-title">Edit Banner</h3>
        </div>
    </div>
</div>
<!-- /Page Header -->

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Form</h4>
            </div>
            <div class="card-body">
                <form action="{{ route('banners.update', $banner->id) }}" method="post" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    @include('admin.banner._form', ['buttonText' => __('Edit')])
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/banner/index.blade.php
@extends('layouts.admin')
@section('page_title', 'Banners')
@section('container')

<!-- Page Header -->
<div class="page-header">
    <div class="row">
        <div class="col">
            <button class="btn btn-primary">
                <a href="{{ route('banners.create') }}">
                    <h3 class="page-title">Add Banner</h3>
                </a>
            </button>
        </div>
    </div>
</div>
<!-- /Page Header -->

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Banners</h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table mb-0">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Banner</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($banners as $banner)
                                <tr>
                                    <td>{{ $banner->id }}</td>
                                    <td>
                                        <img src="{{ asset($banner->banner) }}" alt="banner" width="100" height="100">
                                    </td>
                                    <td>
                                        <a href="{{ route('banners.edit', $banner->id) }}">
                                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                        </a>
                                             | <a class="delete-row" href="{{ route('banners.destroy', $banner->id) }}">
                                                 <i class="fa fa-trash-o" style="color:red" aria-hidden="true"></i>
                                             </a>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="3" align="center">No banner found</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection